services:

##########################################
##
## wordpress / global networking
##
##########################################

    wordpress-proxy:

        container_name: wordpress-proxy

        image: softwareshinobi/docker-container-proxy

        restart: unless-stopped

        volumes:

            - /var/run/docker.sock:/tmp/docker.sock:ro

            - /var/docker/nginx/html:/usr/share/nginx/html

            - /var/docker/nginx/certs:/etc/nginx/certs

            - /var/docker/nginx/vhost:/etc/nginx/vhost.d

        ports:

            - 80:80

            - 443:443

        logging:

            options:

                max-size: "10m"

                max-file: "3"

    wordpress-letsencrypt:

        container_name: wordpress-letsencrypt

        image: jrcs/letsencrypt-nginx-proxy-companion

        restart: unless-stopped

        volumes_from:

            - wordpress-proxy

        volumes:

            - /var/run/docker.sock:/var/run/docker.sock

            - /var/docker/nginx/acme:/etc/acme.sh

        environment:

            DEFAULT_EMAIL: troy@softwareshinobi.com

##########################################
##
## wordpress / relational data
##
##########################################

    wordpress-database:

        container_name: wordpress-database

        image: mariadb:latest

        restart: unless-stopped
        
        volumes:

            - /volumes/database:/var/lib/mysql

        ports:

            - "127.0.0.1:3306:3306"
                    
        environment:

            MYSQL_ROOT_PASSWORD: aggiepride

            MYSQL_DATABASE: wordpress

            MYSQL_USER: wordpress

            MYSQL_PASSWORD: wordpress

            
    wordpress-phpmyadmin:

        container_name: wordpress-phpmyadmin

        image: beeyev/phpmyadmin-lightweight

        depends_on:

           - wordpress-database

        links:

           - wordpress-database

        ports:

            - "127.0.0.1:3380:80"

        environment:

            PMA_HOST: wordpress-database

            VIRTUAL_HOST: database.example.org

            LETSENCRYPT_HOST: database.example.org

##########################################
##
## wordpress / server
##
##########################################

    wordpress-server:

        container_name: wordpress-server

        image: wordpress:latest

        restart: unless-stopped

        depends_on:

            - wordpress-database

        volumes:

            - /volumes/wordpress/:/var/www/html

        ports:

            - "127.0.0.1:8000:80"
 
        environment:

            WORDPRESS_DB_HOST: wordpress-database:3306

            WORDPRESS_DB_USER: wordpress

            WORDPRESS_DB_PASSWORD: wordpress

            WORDPRESS_DB_NAME: wordpress

            VIRTUAL_HOST: example.org

            LETSENCRYPT_HOST: example.org

